"use client";

import { useState } from "react";
import { Copy, FileDown, Link2, Check } from "lucide-react";
import { Button } from "@/src/shared/components/ui/button";
import { usePreferences } from "@/src/shared/context/PreferencesContext";
import { checkerService } from "../services/checker.service";
import { CheckerInput, CheckerResult } from "../types";

interface CheckerExportActionsProps {
  input: CheckerInput;
  result: CheckerResult;
}

export function CheckerExportActions({ input, result }: CheckerExportActionsProps) {
  const { t, language } = usePreferences();
  const [copied, setCopied] = useState(false);
  const [linkCopied, setLinkCopied] = useState(false);

  const handleCopy = async () => {
    const text = checkerService.buildSummaryText(input, result, language);
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    const url = checkerService.buildShareUrl(input);
    await navigator.clipboard.writeText(url);
    setLinkCopied(true);
    setTimeout(() => setLinkCopied(false), 2000);
  };

  const handleExportPdf = () => {
    const text = checkerService.buildSummaryText(input, result, language);
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>FOP Eligibility Report — Flowiq</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; max-width: 700px; margin: 0 auto; color: #111; }
            h1 { font-size: 22px; margin-bottom: 8px; }
            h2 { font-size: 16px; margin-top: 24px; color: #444; }
            p, li { font-size: 14px; line-height: 1.6; color: #333; }
            .badge { display: inline-block; background: #f0f0f0; padding: 4px 12px; border-radius: 6px; font-weight: 600; }
            ul { padding-left: 20px; }
          </style>
        </head>
        <body>
          <h1>FOP Eligibility Report</h1>
          <p style="color:#666">Generated by Flowiq Business Guide</p>
          <pre style="white-space:pre-wrap;font-family:inherit">${text}</pre>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="outline"
        size="sm"
        className="rounded-lg text-xs"
        onClick={handleExportPdf}
      >
        <FileDown className="mr-1.5 h-3.5 w-3.5" />
        {t("businessGuide.checker.export.pdf")}
      </Button>
      <Button
        variant="outline"
        size="sm"
        className="rounded-lg text-xs"
        onClick={handleCopy}
      >
        {copied ? (
          <Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />
        ) : (
          <Copy className="mr-1.5 h-3.5 w-3.5" />
        )}
        {copied
          ? t("businessGuide.checker.export.copied")
          : t("businessGuide.checker.export.copy")}
      </Button>
      <Button
        variant="outline"
        size="sm"
        className="rounded-lg text-xs"
        onClick={handleShare}
      >
        {linkCopied ? (
          <Check className="mr-1.5 h-3.5 w-3.5 text-emerald-500" />
        ) : (
          <Link2 className="mr-1.5 h-3.5 w-3.5" />
        )}
        {linkCopied
          ? t("businessGuide.checker.export.linkCopied")
          : t("businessGuide.checker.export.share")}
      </Button>
    </div>
  );
}
